# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 82375022c199fb6ad67ddd8a6898509c616c0c9a87dd0b5e4ea2523a25653ec2d41937e14ec419c0d1d278ecedd7d8d5cf2f45471bb8dee8a351b9176947c6ee

test:
  secret_key_base: 2ac8a9002084c3d9ce61ad39753569a3b74adb8db1c45402b8b23ff0a12bf4b1b18f5d354f4a2353dd9b23548e7610d726e6a84598776408edc543da9dea0df7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
